M48
; DRILL file KiCad 10.0.1 date 2026-05-09T19:44:13
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-09T19:44:13+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
%
G90
G05
T1
X107.1Y-82.1
X107.1Y-107.9
X132.9Y-82.1
X132.9Y-107.9
M30
